/**
 * Onboard a new organization to staging
 * Creates the org in Stytch, then outputs SQL to run via db-shell
 *
 * Usage: node --experimental-strip-types onboard.ts <org-name> <org-slug> <admin-email>
 */
import {B2BClient} from 'stytch'

const [orgName, orgSlug, adminEmail] = process.argv.slice(2)

if (!orgName || !orgSlug || !adminEmail) {
  console.error('Usage: node --experimental-strip-types onboard.ts <org-name> <org-slug> <admin-email>')
  process.exit(1)
}

// Validate required env vars for Stytch
const requiredEnvVars = ['STYTCH_PROJECT_ID', 'STYTCH_SECRET', 'STYTCH_DOMAIN'] as const
for (let envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    console.error(`Error: ${envVar} is required`)
    process.exit(1)
  }
}

// Initialize Stytch client
const stytch = new B2BClient({
  project_id: process.env.STYTCH_PROJECT_ID!,
  secret: process.env.STYTCH_SECRET!,
  custom_base_url: process.env.STYTCH_DOMAIN!,
})

// Escape single quotes for SQL
function sqlEscape (str: string): string {
  return str.replace(/'/g, "''")
}

try {
  // 1. Create org in Stytch
  console.error(`Creating organization "${orgName}" (slug: ${orgSlug}) in Stytch...`)
  let orgResponse = await stytch.organizations.create({
    organization_name: orgName,
    organization_slug: orgSlug,
  })
  let stytchOrgId = orgResponse.organization.organization_id
  console.error(`  Created Stytch org: ${stytchOrgId}`)

  // 2. Create admin member in Stytch
  console.error(`Creating admin member ${adminEmail} in Stytch...`)
  let memberResponse = await stytch.organizations.members.create({
    organization_id: stytchOrgId,
    email_address: adminEmail,
    create_member_as_pending: false,
  })
  let stytchMemberId = memberResponse.member_id
  console.error(`  Created Stytch member: ${stytchMemberId}`)

  // 3. Output SQL for database (to be run via db-shell)
  let sql = `
-- Onboard org: ${orgName} (${orgSlug})
-- Generated by onboard.ts

INSERT INTO orgs (id, slug, name) VALUES (
  '${sqlEscape(stytchOrgId)}',
  '${sqlEscape(orgSlug)}',
  '${sqlEscape(orgName)}'
);

INSERT INTO users (id, email, "orgId", role) VALUES (
  '${sqlEscape(stytchMemberId)}',
  '${sqlEscape(adminEmail)}',
  '${sqlEscape(stytchOrgId)}',
  'admin'
);
`.trim()

  // Output SQL to stdout (can be piped to db-shell)
  console.log(sql)

  console.error('\nStytch setup complete!')
  console.error(`  Org ID: ${stytchOrgId}`)
  console.error(`  Org Slug: ${orgSlug}`)
  console.error(`  Org Name: ${orgName}`)
  console.error(`  Admin: ${adminEmail} (${stytchMemberId})`)
  console.error('\nSQL has been output above. Run it via db-shell to complete setup.')
} catch (err: any) {
  console.error('\nError during onboarding:', err.message || err)
  process.exit(1)
}
