// Oxlint owns ordinary JavaScript/TypeScript rules and TS7-native typechecking; ESLint handles Svelte and plugin-based style rules.
import {defineConfig} from 'oxlint'

export default defineConfig({
  'plugins': [
    'typescript',
  ],
  'jsPlugins': [],
  'categories': {
    'correctness': 'off',
  },
  'options': {
    'typeAware': true,
    'typeCheck': true,
  },
  'env': {
    'builtin': true,
    'browser': true,
  },
  'ignorePatterns': [
    '**/node_modules/**/*',
    '**/.svelte-check/**/*',
    '**/out/**/*',
    '**/dist/**/*',
    '**/.vscode-test/**/*',
    'ui/tests/results',
    'cli/*.tgz',
    'create/*.tgz',
    '**/notes.md',
    '**/todo.md',
    '**/.gitcommit',
    '**/.DS_Store',
    '**/.vscode/settings.json',
    'vscode/*.vsix',
    'vscode/LICENSE.md',
    '**/CLAUDE.md',
    '**/.claude',
    '**/.env',
    'lang/parser.js',
    '**/*.svelte',
  ],
  'rules': {
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unassigned-vars': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': 'error',
    'no-useless-assignment': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'preserve-caught-error': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'no-array-constructor': 'error',
    'no-unused-expressions': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
  },
  'overrides': [
    {
      'files': [
        '**/*.ts',
        '**/*.tsx',
        '**/*.mts',
        '**/*.cts',
      ],
      'rules': {
        'constructor-super': 'off',
        'getter-return': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-redeclare': 'off',
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-undef': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-var': 'error',
        'no-with': 'off',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
      },
    },
    {
      'files': [
        '**/*.ts',
      ],
      'rules': {
        'typescript/no-floating-promises': [
          'error',
          {
            'checkThenables': true,
          },
        ],
      },
    },
    {
      'files': [
        'scripts/**/*.js',
      ],
      'rules': {
        'no-console': 'off',
        'no-unused-expressions': 'off',
      },
      'globals': {
        'AsyncDisposableStack': 'readonly',
        'DisposableStack': 'readonly',
        'SuppressedError': 'readonly',
        '$': 'readonly',
        'Fail': 'readonly',
        'ProcessOutput': 'readonly',
        'ProcessPromise': 'readonly',
        'VERSION': 'readonly',
        'YAML': 'readonly',
        'argv': 'readonly',
        'bus': 'readonly',
        'cd': 'readonly',
        'chalk': 'readonly',
        'defaults': 'readonly',
        'dotenv': 'readonly',
        'echo': 'readonly',
        'expBackoff': 'readonly',
        'fs': 'readonly',
        'glob': 'readonly',
        'globby': 'readonly',
        'kill': 'readonly',
        'log': 'readonly',
        'minimist': 'readonly',
        'nothrow': 'readonly',
        'os': 'readonly',
        'parseArgv': 'readonly',
        'path': 'readonly',
        'ps': 'readonly',
        'question': 'readonly',
        'quiet': 'readonly',
        'quote': 'readonly',
        'quotePowerShell': 'readonly',
        'resolveDefaults': 'readonly',
        'retry': 'readonly',
        'sleep': 'readonly',
        'spinner': 'readonly',
        'stdin': 'readonly',
        'syncProcessCwd': 'readonly',
        'tempdir': 'readonly',
        'tempfile': 'readonly',
        'tmpdir': 'readonly',
        'tmpfile': 'readonly',
        'updateArgv': 'readonly',
        'useBash': 'readonly',
        'usePowerShell': 'readonly',
        'usePwsh': 'readonly',
        'version': 'readonly',
        'versions': 'readonly',
        'which': 'readonly',
        'within': 'readonly',
      },
      'env': {
        'es2021': true,
        'node': true,
      },
    },
    {
      'files': [
        '**/*.{js,mjs,cjs,ts,svelte}',
      ],
      'rules': {
        'prefer-promise-reject-errors': [
          'error',
        ],
        'require-await': [
          'error',
        ],
        'max-depth': [
          'error',
          4,
        ],
        'no-nested-ternary': [
          'error',
        ],
        'no-useless-assignment': 'off',
        'no-duplicate-imports': [
          'error',
        ],
        'no-restricted-imports': [
          'error',
          {
            'paths': [
              {
                'name': '@lucide/svelte',
                'message': 'Import Lucide icons directly from @lucide/svelte/icons/<icon> so Vite tests do not load the full icon barrel.',
              },
            ],
          },
        ],
        'no-var': [
          'error',
        ],
        'prefer-const': 'off',
        'no-case-declarations': 'off',
        'no-unused-vars': [
          'error',
          {
            'argsIgnorePattern': '^_',
            'varsIgnorePattern': '^_',
          },
        ],
        'typescript/consistent-type-imports': [
          'error',
          {
            'prefer': 'type-imports',
            'fixStyle': 'inline-type-imports',
          },
        ],
        'typescript/no-explicit-any': 'off',
      },
    },
  ],
})
