name: CI

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          submodules: "true"
          token: ${{ secrets.CI_READ_TOKEN }}

      - uses: ./.github/actions/setup
      - name: Lint
        working-directory: cloud
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          submodules: "true"
          token: ${{ secrets.CI_READ_TOKEN }}

      - uses: ./.github/actions/setup

      - name: Ensure migrations checked in
        working-directory: cloud
        run: |
          pnpm db:generate
          if [ -n "$(git status --porcelain)" ]; then
            git status
            exit 1
          fi

      - name: Playwright install
        working-directory: cloud
        run: npx playwright install --with-deps chromium

      - name: Test
        working-directory: cloud
        run: pnpm test
        env:
          GOOGLE_CREDENTIALS_CONTENT: ${{ secrets.BIGQUERY_TEST_CREDS }}
          STYTCH_PROJECT_ID: project-test-34239fee-cb48-4366-a8db-afe04e2cf07d
          STYTCH_SECRET: ${{ secrets.STYTCH_TEST_SECRET }}
          STYTCH_DOMAIN: https://forested-taurus-9604.customers.stytch.dev
          VITE_STYTCH_PUBLIC_TOKEN: public-token-test-9ca7ff1b-435c-4a2f-b74b-18f919494205
          CI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          CI_GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}

      - name: Upload failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: UI test diffs
          path: cloud/tests/results/**

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          submodules: "true"
          token: ${{ secrets.CI_READ_TOKEN }}

      - uses: ./.github/actions/setup
        with:
          core-ssh-key: ${{ secrets.CORE_DEPLOY_SSH_KEY }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::772069004272:role/ci-deploy
          aws-region: us-east-1

      - name: Deploy
        run: ./cloud/scripts/deploy.sh production
        env:
          VITE_STYTCH_PUBLIC_TOKEN: ${{ secrets.VITE_STYTCH_PUBLIC_TOKEN }}

      - name: Deploy Lambda function
        working-directory: cloud/lambda/screenshot
        run: bash deploy.sh 772069004272
