name: CI

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          path: cloud
          lfs: true

      - uses: ./cloud/.github/actions/setup
        with:
          core-ssh-key: ${{ secrets.CORE_DEPLOY_SSH_KEY }}

      - name: Lint
        working-directory: cloud
        run: pnpm lint

      - name: Ensure migrations checked in
        working-directory: cloud
        run: |
          pnpm db:generate
          if [ -n "$(git status --porcelain)" ]; then
            git status
            exit 1
          fi

      - name: Download flights db
        working-directory: core/examples/flights
        run: pnpm run setup

      - name: Playwright install
        working-directory: cloud
        run: npx playwright install --with-deps chromium

      - name: Test
        working-directory: cloud
        run: pnpm test
        env:
          BIGQUERY_TEST_CREDS: ${{ secrets.BIGQUERY_TEST_CREDS }}
          STYTCH_PROJECT_ID: project-test-eaaff9fe-3c7f-486e-90b9-23d249388064
          STYTCH_SECRET: ${{ secrets.STYTCH_TEST_SECRET }}
          STYTCH_DOMAIN: https://futuristic-coil-3570.customers.stytch.dev
          VITE_STYTCH_PUBLIC_TOKEN: public-token-test-340ad761-ec19-47c0-b53e-094d5f65bd3a
          CI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
          CI_GITHUB_APP_CLIENT_SECRET: ${{ secrets.CI_GITHUB_APP_CLIENT_SECRET }}

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v5
        with:
          path: cloud
          lfs: true

      - uses: ./cloud/.github/actions/setup
        with:
          core-ssh-key: ${{ secrets.CORE_DEPLOY_SSH_KEY }}

      - name: Vite build
        working-directory: cloud
        run: pnpm build
        env:
          VITE_STYTCH_PUBLIC_TOKEN: ${{ secrets.VITE_STYTCH_PUBLIC_TOKEN }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::772069004272:role/ci-deploy
          aws-region: us-east-1

      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v2

      # todo: in theory this action can persist the cache between runs, which would be nice
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cloud/server/Dockerfile
          push: false
          tags: |
            772069004272.dkr.ecr.us-east-1.amazonaws.com/graphene/cloud:latest
            772069004272.dkr.ecr.us-east-1.amazonaws.com/graphene/cloud:${{ github.sha }}

      ######################################################################
      # Past this point, we're pretty commited to the deploy and don't expect any steps to fail

      - name: Migrate DB
        working-directory: cloud
        run: pnpm db:migrate
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      # NB that AppRunner is currently configured to auto-update to latest, so pushing implicitly deploys
      - name: Push image
        run: |
          docker push 772069004272.dkr.ecr.us-east-1.amazonaws.com/graphene/cloud:latest
          docker push 772069004272.dkr.ecr.us-east-1.amazonaws.com/graphene/cloud:${{ github.sha }}
