// Evidence has a complex theme loading system that we don't really want to keep.
// This was generated by copying the runtime export of $evidence/themes from the evidence sample app.
export const themes = {
  light: {
    colors: {
      primary: '#EE9174',
      accent: '#c2410c',
      'base-100': '#ffffff',
      info: '#0284c7',
      positive: '#16a34a',
      warning: '#f8c900',
      negative: '#dc2626',
      'primary-content': '#f6f8fb',
      'accent-content': '#fbf7f6',
      'base-200': '#f7f7f7',
      'base-300': '#d6d6d6',
      'base-heading': '#060606',
      'base-content': '#2c2c2c',
      'base-content-muted': '#717171',
      'info-content': '#030709',
      'positive-content': '#040906',
      'negative-content': '#fbf6f6',
      'warning-content': '#0a0803',
    },
    colorPalettes: {
      default: ['#EE9174', '#59A48B', '#D6AFC6', '#78B0D5', '#D5AE4E', '#C16864', '#A7CCC3'],
    },
    colorScales: {
      default: ['#59A48B', '#78B0D5'],
    },
  },
  dark: {
    colors: {
      primary: '#7A8DAB',
      accent: '#fdba74',
      'base-100': '#09090b',
      info: '#38bdf8',
      positive: '#4ade80',
      warning: '#fbbf24',
      negative: '#f87171',
      'primary-content': '#030609',
      'accent-content': '#090603',
      'base-200': '#111113',
      'base-300': '#29292b',
      'base-heading': '#f8f8f9',
      'base-content': '#cacacb',
      'base-content-muted': '#7b7b7c',
      'info-content': '#030809',
      'positive-content': '#040906',
      'negative-content': '#090303',
      'warning-content': '#090803',
    },
    colorPalettes: {
      default: ['#A7CCC3', '#EE9174', '#59A48B', '#D6AFC6', '#78B0D5', '#D5AE4E', '#C16864'],
    },
    colorScales: {
      default: ['#A7CCC3', '#D6AFC6'],
    },
  },
}
